# Plugins
gems:
- jekyll-sitemap
- jekyll-gist
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Riverside Postdoctoral Association"
email: "postdoc@ucr.edu"
description: "Riverside Postdoctoral Association"
#baseurl: "/"
url: "https://rpa.ucr.edu/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-141608372-1"
googleAnalyticsSiteUrl: "rpa.ucr.edu"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "RPA"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Riverside Postdoctoral Association"
organizerEmail: "postdoc@ucr.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://rpa.ucr.edu/"

# Head
metaKeywords: "event, postdoc, RPA, UCR, California"
twitterAccount: "@UCRPostdoc"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/board/", text: "Board"}
 - {permalink: "/events/", text: "Events"}
 - {permalink: "/news/", text: "News"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/donate/", text: "Donate"}
#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.png"
heroTitle: "Riverside Postdoctoral Association <typeout>"
# eventDate: "September - November, 2014"
typeoutTextValues: '"RPA", ""'
#typeoutFallback: "RPA"
#heroButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Riverside Postdoctoral Association"
aboutText1: "Welcome to the Riverside Postdoctoral Association (RPA) webpage. The RPA is an association run by postdocs for postdocs. The RPA works to improve the quality of life of postdoctoral researchers and their families at UCR by building a community and providing and supporting activities, both academic and otherwise, for all its members."
aboutBlock:
 - {title: "Communicate", image: "Communicate.jpg", text: "your research" }
 - {title: "Explore", image: "Explore.jpg", text: "the diversity of postdoctoral research performed at UCR" }
 - {title: "Collaborate", image: "Collaborate.jpg", text: "with other postdocs" }
 - {title: "Invent", image: "Invent2.jpg", text: "a world-changing idea" }

# Statistic Block
statisticBlockImage: "raspberry.png"
statisticBlock:
 - {count: "220", specialCharacter: "+", info: "UCR Postdocs", detail: ""}
 - {count: "31", specialCharacter: "+", info: "Departments", detail: ""}
 - {count: "90", specialCharacter: "+", info: "Events organized", detail: ""}
 - {count: "5", specialCharacter: "", info: "Years of RPA", detail: ""}

# Latest News Block
latestNewsTitle: "Latest news"

# Subscribe Block
subscribeImage: "blue.png"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://lists.ucr.edu/cgi-bin/mailman/listinfo/rpa-postdoc"
subscribeInfo: "Subscribe to our Newsletter and stay tuned!"


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "RPA"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueSmallImage4: "venue_4.jpg"
venueTitle: "See more photos!"
venueFeatures: ["test"]
venueLink:  
 - {link: "https://photos.app.goo.gl/MFU3FGiJEmcwCPg26", text: "Become a speaker"}

# Tweets Feed Block
tweetsFeedImage: "orange.png"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "ucrpostdocsymposium2019"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"


# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://www.instagram.com/ucrpostdoctoral/", icon: "instagram"}
# - {link: "https://twitter.com/intent/user?screen_name=UCRPostdoc", icon: "twitter"}
# - {link: "https://facebook.com/UC-Riverside-Postdoctoral-Association-460810420930605", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://rpa.ucr.edu/", text: "RPA"}
   - {link: "https://graduate.ucr.edu/", text: "Graduate Division"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:postdoc@ucr.edu", text: "postdoc@ucr.edu"}
   - {link: "https://www.instagram.com/ucrpostdoctoral/", text: "Instagram"}
   - {link: "https://twitter.com/intent/user?screen_name=UCRPostdoc", text: "Twitter"}
   - {link: "https://facebook.com/UC-Riverside-Postdoctoral-Association-460810420930605", text: "Facebook"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "RPA"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Donate"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Get Involved"
hackathonImage: "blue.png"
hackathonRows:
 - {title: "Support the Riverside Postdoctoral Association", image: "getinvolved.jpg", details: "Support for the Riverside Postdoctoral Association funds to help build a community for all the UCR Postdoctoral Researchers. 
Make a gift to support the Riverside Postdoctoral Association online at https://myadv.ucr.edu/CHASS/Postdoctoral. 
For more information, please contact Sharma Yamijala, Treasurer of RPA, at postdoc@ucr.edu."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
